### ISSUE TITLE
Allow customization of meta title and description

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/workers-docs#385]
It would be nice to have frontmatter fields for each Markdown page, to allow custom meta title and descriptions for each page. 

```yaml
---
title: "Deploying React Apps with Workers"
meta_title: "Tutorial: Deploying React Apps with Workers - Cloudflare Workers"
meta_description: "Learn how to deploy React applications to Cloudflare Workers with this interactive tutorial, designed to help beginners deploy their applications to Cloudflare's serverless platform."
---
```

This will probably involve checking for the existence of fields for a post's frontmatter, inside of the `post` template, and replacing the `<meta>` tags if those fields are found.

Worth mentioning that the meta description (and Facebook/Twitter embed description) for _every_ page in the docs is `Use Cloudflare’s APIs and edge network to build secure, ultra-fast applications.` - this could be drastically improved for better clickthrough rates/SEO stuff. 

We may also consider implementing better defaults even if a custom description isn't passed - my initial take would be grabbing X characters from the post content and serving it as the description by default.
